# Generated by Django 3.0.4 on 2020-03-23 03:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('garage', models.DecimalField(decimal_places=1, max_digits=5)),
                ('sqft', models.IntegerField()),
                ('photo_main', models.ImageField(upload_to='photo/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 23, 8, 39, 12, 942179))),
            ],
        ),
    ]
